# Generated by Django 2.1.4 on 2019-10-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='schoolfleas_user',
        ),
    ]
