# Generated by Django 2.1.4 on 2019-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='headimg',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=50, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=30, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(max_length=30, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=500, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.TextField(max_length=500, null=True, verbose_name='用户token'),
        ),
    ]
