# Generated by Django 2.1.4 on 2019-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='S_User',
        ),
    ]
