# Generated by Django 2.1.4 on 2019-10-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191002_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_User',
            new_name='User',
        ),
    ]
