# Generated by Django 2.1.4 on 2019-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=200, null=True, verbose_name='用户token'),
        ),
    ]
