# Generated by Django 2.1.4 on 2019-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191002_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tele',
            field=models.BigIntegerField(max_length=11, null=True, verbose_name='电话'),
        ),
    ]
