# Generated by Django 2.1.4 on 2019-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191002_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tele',
            field=models.BigIntegerField(null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=500, null=True, verbose_name='用户token'),
        ),
    ]
