# Generated by Django 2.1.4 on 2019-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('goods_images', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('goods_status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架'), (2, '待审核')], default=0, verbose_name='商品状态')),
                ('goods_type', models.CharField(choices=[('book', '书籍'), ('newest', '最新'), ('daily', '生活用品'), ('3c', '3c数码'), ('dress', '鞋服美妆'), ('job', '兼职'), ('help', '求助')], max_length=10, verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'SchoolFleas_Goods',
            },
        ),
    ]
