# Generated by Django 2.1.4 on 2019-10-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='SchoolFleasPro_Goods',
        ),
    ]
