# Generated by Django 2.1.4 on 2019-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='judgeType',
            field=models.IntegerField(default=0, verbose_name='购物车or收藏'),
        ),
    ]
