# Generated by Django 2.1.4 on 2019-10-18 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='collect',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcart',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='collect',
            table='SchoolFleasPro_collect',
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='SchoolFleasPro_cart',
        ),
    ]
